# Generated by Django 2.0.2 on 2018-02-24 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookZone', '0002_category_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
