# Generated by Django 2.0.2 on 2018-02-24 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookZone', '0007_auto_20180224_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
