# Generated by Django 2.0.2 on 2018-02-25 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookZone', '0009_auto_20180225_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_pic',
            field=models.ImageField(blank=True, upload_to='bookZone/static/images/authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(blank=True, upload_to='bookZone/static/images/books'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_pic',
            field=models.ImageField(blank=True, upload_to='bookZone/static/images/categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
