# Generated by Django 2.0.2 on 2018-02-26 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookZone', '0010_auto_20180225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='User_Book_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='User_Book_Wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
